### ISSUE TITLE
internal NMBS API used by iRail is being shut down

### ISSUE THREAD

**Issue by rgerbranda** [iRail/iRail#466]
When I go to https://api.irail.be/connections/?to=Noorderkempen&from=Antwerpen-Centraal&format=json

```{"error":500,"message":"Could not get data: This request failed. Please check your query. Error code . Please report this issue at https://github.com/irail/irail/issues/new"}```

It worked till 02/11/2022

**Comment by Bertware** [comment]
The API which was used by iRail has been shut down.

´´´{"ver":"1.21","lang":"eng","id":"g64magxi4q4xym8x","err":"CLIENTVERSION","cInfo":{"code":"VD","url":"Cette fonctionnalité n'est plus disponible. Pour planifier votre voyage, téléchargez la nouvelle app SNCB. / Deze app is niet langer beschikbaar. Om jouw reis te plannen download je best de nieuwe NMBS-app. / This feature is no longer available. To plan your trip, download the new SNCB app. / Diese App wird nicht mehr unterstützt. Für die Planung Ihrer Reise laden sie bitte die neue SNCB App herunter.","msg":""},"svcResL":[]}´´´

This means the connections endpoint needs to be completely re-implemented

**Comment by Bertware** [comment]
This affects other endpoints as well, which also need to be rewritten against other data sources.

**Comment by xivk** [comment]
@Bertware anything I can do to help with this? We have applications relying on this...

**Comment by Bertware** [comment]
I already reverse engineered the new NMBS app earlier, you can test the requests and possibly try to adjust https://github.com/iRail/iRail/blob/master/src/api/data/NMBS/ConnectionsDatasource.php to use the data from the new endpoint.

https://gist.github.com/Bertware/6c8dc535135070854bee90016bf9cc4f

**Comment by Bertware** [comment]
Quickly tested (HTTP is required!) but it seems like a new API key should be obtained by proxying traffic from the new NMBS app through a MITM proxy server which intercepts the requests.

ERROR reason : error : 7501 : _API-Key : Incorrect credential received

**Comment by xivk** [comment]
Ok, thanks for the info, so you're saying the only option to reverse-engineer the new NMBS API, convert the data, and then we are maybe good to go.

**Comment by pietercolpaert** [comment]
Just for context:

iRail still uses the APIs behind the app of SNCB. We agreed to migrate to their GTFS files, on the condition that they would add platform change support to the GTFS files. That however is still not added and we thus still rely on the APIs they now phased out.

Let’s try to repair this asap as we’re doing right now. In the meantime, I’ll reach out to SNCB for a status update.

**Comment by Bertware** [comment]
I also believe the new API is provided by Hafas, just like the old one. This, might make the migration of the connections endpoint relatively easy, but we need to see an example response first.

**Comment by xivk** [comment]
OK, awesome @pietercolpaert 😍 

We have a budget for this as well if that can help make things move or free up some time, my php skill are not almost non-existent!

**Comment by Bertware** [comment]
@Muspah if that's correct it should be fairly easy to fix. If someone can save me the time of reverse engineering the API key I can probably fix at least the connections endpoint today.

**Comment by Muspah** [comment]
It's what I can remember at least, we're doing GTFS (-RT) and mix in platform information from querying SNCB. 

I might take a look too if I have some time available, traveling back to Belgium atm with a railway company that actually does functional open data, lol. MITM'ing from the train is a misery, sorry.

**Comment by Bertware** [comment]
NMBS has temporarily restored the old app infrastructure in order to give iRail time to update. In two weeks the service will be shut down again, but this should give a decent amount of time to make the required changes.

**Comment by pietercolpaert** [comment]
@Bertware What’s your idea of what should happen? Move to the new API? Should we ask an API key to SNCB for the new API?

**Comment by pietercolpaert** [comment]
Would it be feasible to transition the API to internally use our Linked Connections at https://graph.irail.be/sncb/connections?

**Comment by jbelien** [comment]
I most probably also can help with this if needed.
Migrating to the new SNCB/NMBS API seems the logic choice (with a proper API key).

**Comment by Muspah** [comment]
Just grab the API key from the app for now, it works fine.

x-api-key IOS-v0001-20190214-YKNDlEPxDqynCovC2ciUOYl8L6aMwU4WuhKaNtxl
User-Agent BelgianTrain/11 CFNetwork/1335.0.3 Darwin/21.6.0

Departures (stationboard)
https://mobile-riv.api.belgianrail.be/api/v1.0/dacs?query=DeparturesApp&UicCode=8833134&FromDate=2022-11-04%2017%3A14%3A37&Count=100

Arrivals (stationboard)
https://mobile-riv.api.belgianrail.be/api/v1.0/dacs?query=ArrivalsApp&UicCode=8833134&FromDate=2022-11-04%2017%3A20%3A19&Count=100

Journey / trip info, first call
https://mobile-riv.api.belgianrail.be/riv/v1.0/journey?trainFilter=S206466&originExtId=8833134&destExtId=8833001&date=2022-11-04&time=17%3A26%3A00&lang=nl

Journey / stops info, second call
https://mobile-riv.api.belgianrail.be/riv/v1.0/journey/detail?id=1%7C5778%7C11%7C80%7C4112022&lang=nl

Journey planner Leuven -> Antwerpen CS
https://mobile-riv.api.belgianrail.be/riv/v1.0/journey?originExtId=8833001&destExtId=8821006&lang=nl&date=2022-11-04&time=17%3A21%3A18&searchForArrival=0&originWalk=1%2C%2C2000&originBike=0&originCar=0&destWalk=1%2C%2C2000&destBike=0&destCar=0&minChangeTime=0&products=116&numF=6

**Comment by pietercolpaert** [comment]
@jbelien awesome! Let's see how to proceed first

@Muspah Ugh Graphql... Fancy new technology that does the same but differently ;)

@Muspah I now asked the SNCB whether we can get a proper API key. Let's see how to proceed, but we can definitely start coding against your URLs. Thanks for the effort!

**Comment by Muspah** [comment]
@pietercolpaert If you want to play nice with NMBS and ask for a key or just use one from the app is up to you guys. I personally don't care, they should fix GTFS-RT if they want to cry about it. Let them call NS in Utrecht (or SdK, lol) and ask for advice.

Using the iOS key at least gives the opportunity to start developing against the new API's for now.

**Comment by Bertware** [comment]
> @Muspah Ugh Graphql... Fancy new technology that does the same but differently ;)

Only for the stations endpoint which we don't use anyway. Ticketing as well, which is a new type of data.





> Just grab the API key from the app for now, it works fine. It's HAFAS indeed proxied through some SNCB layer.

It's Hafas open api 2.19 through a proxy, which is fantastic news, since this API is easier to parse - and I wrote one of the manuals on how to use almost this identical version as an API consumer 🎉.

Currently working on a rewrite of the parser to switch from the internal API to the open API response format.

**Comment by Muspah** [comment]
Ah okay, didn't recognize the exact scheme, HAFAS is not that common in NL.

**Comment by Bertware** [comment]
> Ah okay, didn't recognize the exact scheme, HAFAS is not that common in NL.

You were right about the proxy though, there is some data being added which is not included in the official public documentation of other Hafas instances: Legs now include the occupancy on the origin and destination.

```
"CommercialInfo": {
                "Occupancy": {
                  "Level": 1
                }
              }
```

It should be possible to use this as a fallback when spitsgids data is not available, which would immediately enrich all apps already showing spitsgids data (I'm aware of the reporting being broken, but spitsgids needing love and a new datastore is something for when this migration is done.)

---

The feature branch for resolving this issue is available on staging.api.irail.be, and can be recognized by the "version: 1.2" at the top of the responses. Only the connections endpoint has been migrated as of right now.

https://staging.api.irail.be/connections/?to=Gent-Sint-Pieters&from=Antwerpen-Centraal&format=json

Filtering on trains (including or excluding international trains) does not work at all right now, since I do not know the values which should be passed to the products filter.

**Comment by Bertware** [comment]
Liveboards are now almost completely re-implemented, only platform changes, train cancelled state and time selection has not been implemented yet. 

Train left/arrived (`left`) and extra train yes/no (`isExtra`) will likely no longer work even when the implementation is finished, due to missing data in the new API

**Comment by pietercolpaert** [comment]
@jbelien and others who’d like to help out: can you join the OpenPlanner slack for exchanging ideas? https://join.slack.com/t/openplanner/shared_invite/zt-781ymf0m-3SmsaDS40b_by8MXimV9aQ → channel irail-api

**Comment by pietercolpaert** [comment]
> Liveboards are now almost completely re-implemented, only platform changes, train cancelled state and time selection has not been implemented yet.
> 
> Train left/arrived (`left`) and extra train yes/no (`isExtra`) will likely no longer work even when the implementation is finished, due to missing data in the new API

Awesome work Bert! Hope we can also keep using this to validate our own route planning results if we do the route calculations based on Linked Connections

**Comment by derhuerst** [comment]
@Bertware Do you know how many differences there are compared to other HAFAS "open APIs"?

There are some clients out there, and I wonder if they are compatible with the API provided by NMBS. (I can't find the other ones right now, just found my own 🙈 https://github.com/public-transport/hafas-client/pull/134)

**Comment by Bertware** [comment]
> @Bertware Do you know how many differences there are compared to other HAFAS "open APIs"?
> 
> There are some clients out there, and I wonder if they are compatible with the API provided by NMBS. (I can't find the other ones right now, just found my own see_no_evil [public-transport/hafas-client#134](https://github.com/public-transport/hafas-client/pull/134))

As far as I know the only difference is the addition of `CommercialInfo`. Other than that it seems like they still use the standard (old? Open API 2.19) `Product` object, instead of wrapping it in a `Products` array and defining the vehicle type at a stop as `ProductAtStop` (As I've seen before in v2.25)

**Comment by Bertware** [comment]
The vehicle endpoint seems to be harder to re-implement.

There are 2 endpoints the API uses:
- The first one, `Hafas Journey Detail Service`, is available through `GET https://mobile-riv.api.belgianrail.be/riv/v1.0/journey/detail?id=1|750|0|80|8112022&lang=nl`. For this request, we need a journeyDetailRef of the form `1|<journey id>|0|80|<date>`. Date is known, but we need to know the journey id if we want to support train searches using train numbers such as "IC587". The following trip_ids are available in the GTFS feed (possibly also produced by Hacon) `88____:049::8895208:8895505:3:2415:20221202`, but they don't seem to help. The old application uses a TrainSearch endpoint for this, but this endpoint is no longer available in the new app (since the new app does not include this functionality, you always have to click through from a routeplanner result or departureboard result.

- The second one, `Hafas Trip Search` is available at `GET https://mobile-riv.api.belgianrail.be/riv/v1.0/journey?trainFilter=IC2415&originExtId=8895208&destExtId=8895505`. This is the routeplanner endpoint with a train filer, which works directly using the train number, but requires the start and end point of the train to be known. Here we could use an index file based on the data available in graph.irail.be, in order to match each train with a departure and arrival station. This would require a train index to be implemented on graph.irail.be, as this currently does not exist yet. An alternative would be building this index directly of the NMBS GTFS, but this would likely be needlessly complicated compared to an index on graph.irail.be.

The easiest would be using the journey ids in the first option, but if that's not possible we should probably implement the second option. Any ideas on how to obtain a journey id are welcome! I'm aware we could scrape liveboards, but that does not seem to be a fail-proof situation, and would be a needless burden on the NMBS.

**Comment by Muspah** [comment]
SNCB's GTFS is output from HAFAS indeed.

**Comment by Bertware** [comment]
In `88____:049::8895208:8895505:3:2415:20221202`, 8895208 and 8895505 are  the origin id and the destination id. Somehow I overlooked that the train number can be fetched from trip_short_name, so trips.txt should be sufficient as an index for the vehicle endpoint (for now, a cronjob approach for fetching the index is far from ideal, but it cannot be loaded on demand since it takes some processing time).

**Comment by Bertware** [comment]
The vehicle endpoint has been re-implemented as well, meaning all endpoints have at least basic functionality while fetching data from the new internal API.

Regarding the vehicle endpoint:
- Currently, using the vehicle name is required (and not properly filtered, so it might be that only ids of the form "IC123" are working. This should be fixable though with some more work
- Platforms are missing from the first and last stop of a vehicle, this can be fixed
- Platforms are missing from all intermediate stops of a vehicle as well, this cannot be fixed right now due to missing data at the source
- Alerts, messages are not implemented right now

**Comment by Bertware** [comment]
Platform numbers for the vehicle endpoint are back! Along with other bugfixes to various parts of the new code.
Alerts and messages are still missing from the vehicle endpoint, but it should work quite well now.

@jncn @ChristopheVersieux Please start testing your apps against staging.api.irail.be, and report any issues.

** Regarding international traffic: **
 - International trains are shown in the liveboard endpoint
 - Liveboards for stations in other countries cannot be shown. Might be fixable in the distant future.
 - Vehicle data from the vehicle endpoint is not available for international traffic that is not run by the NMBS (e.g. thalys, ICE, eurostar). Might be fixable in the distant future.

**Comment by Bertware** [comment]
@xivk please see the comment above, and test as well by testing your applications against staging.api.irail.be instead of api.irail.be. Report any issues back here so we can see if something broke during the migration.

**Comment by jncn** [comment]
@Bertware, thanks.

I'm getting 404s on all endpoints:
- https://staging.api.irail.be/liveboard/?lang=nl&station=BE.NMBS.008813003
- https://staging.api.irail.be/connections/?lang=nl&to=BE.NMBS.008833001&from=BE.NMBS.008813003
- https://staging.api.irail.be/vehicle/?lang=nl&id=BE.NMBS.IC2143&alerts=true&date=171122

**Comment by DylanVanAssche** [comment]
Seems to work if you drop 'BE.NMBS'.

**Comment by Bertware** [comment]
So support for those BE.NMBS. identifiers has stopped working for some reason, will fix

**Comment by Bertware** [comment]
> @Bertware, thanks.
> 
> I'm getting 404s on all endpoints:
> 
>     * https://staging.api.irail.be/liveboard/?lang=nl&station=BE.NMBS.008813003
> 
>     * https://staging.api.irail.be/connections/?lang=nl&to=BE.NMBS.008833001&from=BE.NMBS.008813003
> 
>     * https://staging.api.irail.be/vehicle/?lang=nl&id=BE.NMBS.IC2143&alerts=true&date=171122

Fixed now! The vehicle can't be found, which needs further investigation, but at least the BE.NMBS.' ids are accepted again.

**Comment by Muspah** [comment]
> * The first one, `Hafas Journey Detail Service`, is available through `GET https://mobile-riv.api.belgianrail.be/riv/v1.0/journey/detail?id=1|750|0|80|8112022&lang=nl`. For this request, we need a journeyDetailRef of the form `1|<journey id>|0|80|<date>`. Date is known, but we need to know the journey id if we want to support train searches using train numbers such as "IC587". The following trip_ids are available in the GTFS feed (possibly also produced by Hacon) `88____:049::8895208:8895505:3:2415:20221202`, but they don't seem to help. The old application uses a TrainSearch endpoint for this, but this endpoint is no longer available in the new app (since the new app does not include this functionality, you always have to click through from a routeplanner result or departureboard result.

We're going to deploy a new version of our poller which will start logging those journeyRef's and their corresponding trip data to see if we're able to find some logic in it. I'm not sure about the 0 and 1, the 80 should be the internal operator code. Still dont care about the high amount of requests to NMBS as long as they dont fix their open data feeds, but having to do additional requests just to find a journey id is not ideal. Or has anyone else already done research into it?

The Dutch HAFAS environment uses the /v2 Open API endpoints, where departure boards contain a journeyRef field. Those endpoints return in "Access Denied" when trying them at NMBS.

**Comment by Bertware** [comment]
I currently implemented a working solution by obtaining vehicle start and end points from the GTFS data, then looking up the journey with a filter (just like the NMBS app does) then calling the journeyDetail endpoint with the correct reference.

The NMBS uses Open API v2 as well, but through their own API, so the endpoint URLs are slightly modified and every transport authority can choose which endpoints they want, so any endpoint not used by the NMBS will not be available.

**Comment by Muspah** [comment]
Yeah I checked your implementation indeed, and it sure is a solution for now, but I'd like to log it for a while and see if we're able to find a pattern or something that would remove the need to make the extra call. We're polling all services running to find platform changes to integrate into our pushfeed, so removing the need to request all journeys once per day to find the reference numbers is a win in the amount of requests that we need to do.

**Comment by derhuerst** [comment]
> […] we need a journeyDetailRef of the form `1|<journey id>|0|80|<date>`. Date is known, but we need to know the journey id if we want to support train searches using train numbers such as "IC587".

Note that, sometimes, the `<date>` part is *not* the date the journey has started on, and with some HAFAS methods/APIs the `<date>` part is just straight up ignored; I don't know enough cases though to recognise a pattern, and I haven't investigated this yet.

>  The following trip_ids are available in the GTFS feed (possibly also produced by Hacon) `88____:049::8895208:8895505:3:2415:20221202`, but they don't seem to help.

AFAIK it's the internal ID in the schedule data that HAFAS has ingested, which often has different IDs (and different groupings of individual journeys).

**Comment by derhuerst** [comment]
@marudor says that the journey IDs are composed as follows: `1|<id>|<cycle>|<pool>|<datum in ddMMyyyy>`, not sure how to determine `cycle` & `pool` though without access to the underlying data.

**Comment by derhuerst** [comment]
> I currently implemented a working solution by obtaining vehicle start and end points from the GTFS data, then looking up the journey with a filter (just like the NMBS app does) then calling the journeyDetail endpoint with the correct reference.

I assume you're using the `journeyMatch` service/method/API for this? If not, do you know about it?

**Comment by Muspah** [comment]
Does it still exist in the Open API version that NMBS is running? I can't seem to find a new, working endpoint for that.

**Comment by Bertware** [comment]
> > I currently implemented a working solution by obtaining vehicle start and end points from the GTFS data, then looking up the journey with a filter (just like the NMBS app does) then calling the journeyDetail endpoint with the correct reference.
> 
> I assume you're using the `journeyMatch` service/method/API for this? If not, do you know about it?

We used `journeyMatch` in the previous implementation, but this endpoint is no longer available. Se we're using the `journey` service in combination with the `TrainFilter` parameter, followed by the `journeyDetail` service with the `id` parameter. This is similar to the implementation in the new official application.

**Comment by Bertware** [comment]
> > @Bertware, thanks.
> > I'm getting 404s on all endpoints:
> > ```
> > * https://staging.api.irail.be/liveboard/?lang=nl&station=BE.NMBS.008813003
> > 
> > * https://staging.api.irail.be/connections/?lang=nl&to=BE.NMBS.008833001&from=BE.NMBS.008813003
> > 
> > * https://staging.api.irail.be/vehicle/?lang=nl&id=BE.NMBS.IC2143&alerts=true&date=171122
> > ```
> 
> Fixed now! The vehicle can't be found, which needs further investigation, but at least the BE.NMBS.' ids are accepted again.

@jncn Did you get a chance to test the fixed version on staging.api.irail.be?

**Comment by Bertware** [comment]
The changes have now been deployed to the production environment at api.irail.be, as the old iRail code would stop working tomorrow when the old app is shut down again.

**Comment by pietercolpaert** [comment]
Something still going wrong with duration here:

http://api.irail.be/connections/?from=mons&to=tournai

![Uploading Screenshot_20221120-202552_BeTrains.jpg…]()

**Comment by Bertware** [comment]
> Something still going wrong with duration here:
> 
> http://api.irail.be/connections/?from=mons&to=tournai
> 
> All durations with more than 1 stop is getting the wrong duration on the full itinerary

Should be fixed now!

I'm leaving this issue open for one more week, so we can handle any minor bug here should we discover any more of them.

**Comment by koeleboe** [comment]
I use the Hyperrail app (instead of using the direct links) and there are still some issues with some trains. I write my issues here as this is related to IRail (I guess).

First, if a train is rerouted (due to an incident on the route), the app doesn't know how to handle it. I don't know if this is an existing issue (IC 708) with the API.  
Next, some trains cannot be opened by the app (like IC1829. 
![316139376_458424006431941_4633044825167604577_n](https://user-images.githubusercontent.com/72651779/203001961-48f977f1-4831-4a86-a106-e61b96df85a4.jpg)
![315528926_663278318685213_7542718494103132918_n](https://user-images.githubusercontent.com/72651779/203001972-1a49bc69-9c6b-4271-b845-d028571c90ff.jpg)
![316231933_1350510055698967_8571347275250749759_n](https://user-images.githubusercontent.com/72651779/203001975-5b7ddbd9-7343-4f6d-9fe8-dbb19cf26d6d.jpg)

**Comment by Bertware** [comment]
> I use the Hyperrail app (instead of using the direct links) and there are still some issues with some trains. I write my issues here as this is related to IRail (I guess).
> 
> First, if a train is rerouted (due to an incident on the route), the app doesn't know how to handle it. I don't know if this is an existing issue (IC 708) with the API. Next, some trains cannot be opened by the app (like IC1829).

Thanks for reporting these issues, something is indeed going wrong on the iRail side for both trains. I've logged the necessary debug data, in combination with the screenshots I should be able to fix this in the evening.

**Comment by koeleboe** [comment]
> > I use the Hyperrail app (instead of using the direct links) and there are still some issues with some trains. I write my issues here as this is related to IRail (I guess).
> > First, if a train is rerouted (due to an incident on the route), the app doesn't know how to handle it. I don't know if this is an existing issue (IC 708) with the API. Next, some trains cannot be opened by the app (like IC1829).
> 
> Thanks for reporting these issues, something is indeed going wrong on the iRail side for both trains. I've logged the necessary debug data, in combination with the screenshots I should be able to fix this in the evening.

Thanks for looking in to this! I added another thing in my original post. I'll update you if I run into more bugs! But thanks for the quick work in this API!

**Comment by hdcore** [comment]
I see two trains IC436 and IC427 who were partially canceled today (after and before Waregem) but with the vehicle api he cannot find the train.
https://api.irail.be/vehicle/?id=IC436&date=211122&format=json&lang=nl
https://api.irail.be/vehicle/?id=IC417&date=211122&format=json&lang=nl
{"error":404,"message":"Vehicle not found"}" 
On the delay certificate page you can verify the partially cancellation.
https://www.belgianrail.be/en/support/delay-certificate.aspx train IC436 and IC417

I also see that the liveboard api don't give any results anymore about the past hours. Before I could see all trains of the day.

**Comment by Bertware** [comment]
Cancelled stops are now detected correctly in the vehicle endpoint.

> I also see that the liveboard api don't give any results anymore about the past hours. Before I could see all trains of the day.

> Some more bugs: apparently it is not possible to go back in time

This seems to be a limitation of the new data source, which we might be able to work around in the distant future.




> I see two trains IC436 and IC417 who were partially canceled today (after and before Waregem) but with the vehicle api he cannot find the train. https://api.irail.be/vehicle/?id=IC436&date=211122&format=json&lang=nl https://api.irail.be/vehicle/?id=IC417&date=211122&format=json&lang=nl {"error":404,"message":"Vehicle not found"}" On the delay certificate page you can verify the partially cancellation. https://www.belgianrail.be/en/support/delay-certificate.aspx train IC436 and IC417

Thanks for these examples! I noticed that IC 417 was cancelled at the first two stops (see screenshot), while IC 436 was cancelled at the last two stops. The current implementation uses the journey planner endpoint with a train filter on top to find the vehicle reference. Therefore if the vehicle is not running the entire trip, it cannot be found. It should be possible to use fallback logic to find trains based on a part of their journey.

![image](https://user-images.githubusercontent.com/1094793/203132017-870772bd-83c7-47a0-97a2-f871ad2a2ef9.png)

**Comment by Bertware** [comment]
> Is there information on the occupation per train?

Occupation is available in the routeplanner data, but is currently not shown since we're focusing on bringing back more critical features first.

**Comment by Bertware** [comment]
> I see two trains IC436 and IC417 who were partially canceled today (after and before Waregem) but with the vehicle api he cannot find the train. https://api.irail.be/vehicle/?id=IC436&date=211122&format=json&lang=nl https://api.irail.be/vehicle/?id=IC417&date=211122&format=json&lang=nl {"error":404,"message":"Vehicle not found"}" On the delay certificate page you can verify the partially cancellation. https://www.belgianrail.be/en/support/delay-certificate.aspx train IC436 and IC417

Fixed! Trains where the origin and/or destination are cancelled are working again now.

**Comment by jncn** [comment]
Folks, thanks a lot for this incredible effort ❤️💪🏼

I have a single small regression to report: previously it was possible to do something like [https://api.irail.be/vehicle/?id=436](https://api.irail.be/vehicle/?id=436), leaving out IC, S, P. Now it seems like these letters are required, e.g. IC436. I have a few user reporting that vehicle search is broken because of this.

**Comment by Muspah** [comment]
The underlying SNCB api requires one to provide the full name for train search, including the type (IC, P, L, ...). Given that trainnumbers are unique, it should be able to look them up in the GTFS routes if the type is not provided, but I'm not sure how that would work in iRail's setup.

**Comment by Bertware** [comment]
Search by just vehicle numbers is working now! Incorrect vehicle types will also be corrected automatically (L 417 will be corrected to IC 417), although this might not work for all S trains.

https://api.irail.be/vehicle/?id=417&date=211122&format=json&lang=nl

**Comment by jncn** [comment]
@Bertware love the timeline here, fixed again before I could even react! Thanks a lot 🙏

**Comment by Muspah** [comment]
There are issues with trains going over the border. For example IC 2143 today:

https://api.irail.be/vehicle/?id=BE.NMBS.IC2143&date=251122&format=json&lang=en&alerts=false

{
"error": 404,
"message": "Vehicle not found"
}

This train is split into two separate trips in GTFS:
82____:007::8200100:8869054:2:2024:20221209
88____:007::8869054:8814001:52:2328:20221209

8869054 is the border stop (where trains wont stop). One can find this trip when using the first stop in Belgium as start point, Aarlen for example.

**Comment by Bertware** [comment]
Thanks for the detailed analysis @Muspah ! The first digits in the UIC code designate the country, so now we simply look for the Belgian part (with a fallback to the international journey if no Belgian part can be found). The journey detail ref describes the train, which is still "1 train" in the HaCon systems, so the output from the internal API is still the same as if it were a national journey.

In the meanwhile I also found another bug which caused needless requests to the NMBS when a journey couldn't be found by its first and last station, I forgot to take pickup and dropoff typs into account. As a result these international trains need only 1 request more than "normal" trains.

Again, thanks for digging in the data, made fixing it a breeze! Your link is working now 😃

**Comment by Muspah** [comment]
It shows how horribly broken NMBS's GTFS is. These virtual border stations show up in GMaps for example too. Wrote a bit about it on Slack too, don't want to go off-topic too much.

**Comment by Muspah** [comment]
Merging the two trips into one seems to work too. HAFAS errors on the border stations only.

**Comment by koeleboe** [comment]
If a train is canceled for the whole journey, it doesn't appear in the departures tab and you can't find it by vehicle either (at least in the app). It seems like the train just doesn't exist. Today: IC 512 (https://api.irail.be/vehicle/?id=512&date=261122&format=json&lang=nl). 
Moreover, 
![316969294_1095909054450515_26799839264034289_n](https://user-images.githubusercontent.com/72651779/204088063-92e986aa-2daf-44f4-b157-707c698c4107.jpg)
![316679328_1112194636104888_8034573277326643944_n](https://user-images.githubusercontent.com/72651779/204088074-e1bb5973-c472-4662-9bf4-0c81d5ab7a78.jpg)

![317109934_538356014866167_1243309199530365878_n](https://user-images.githubusercontent.com/72651779/204088091-90981732-3bae-4852-ba5d-f9d665673fbe.jpg)

**Comment by koeleboe** [comment]
> Thanks for the detailed analysis @Muspah ! The first digits in the UIC code designate the country, so now we simply look for the Belgian part (with a fallback to the international journey if no Belgian part can be found). The journey detail ref describes the train, which is still "1 train" in the HaCon systems, so the output from the internal API is still the same as if it were a national journey.
> 
> In the meanwhile I also found another bug which caused needless requests to the NMBS when a journey couldn't be found by its first and last station, I forgot to take pickup and dropoff typs into account. As a result these international trains need only 1 request more than "normal" trains.
> 
> Again, thanks for digging in the data, made fixing it a breeze! Your link is working now 😃

International trains (like Thalys or Eurostar) are however not working. I don't know if these can be found in the belgian planner.

**Comment by Bertware** [comment]
> If a train is canceled for the whole journey, it doesn't appear in the departures tab and you can't find it by vehicle either (at least in the app). It seems like the train just doesn't exist (instead of showing canceled). Today: IC 512 (https://api.irail.be/vehicle/?id=512&date=261122&format=json&lang=nl).

Cancelled trains are completely absent from the new departure board API, the only way around this I can think of would be to make a second call to the website and get cancelled trains from there. 
We cannot find the journey identifier for cancelled trains either, so therefore we cannot access the vehicle information. Even the NMBS website can't find these trains if you search by train number.

**Comment by koeleboe** [comment]
Thanks for the quick response, makes sense ofcourse! Just another "bug" about hyperrail (maybe it's better in the other topic), but when looking in the feature for the departures at a station, it doesn't load. For example: (https://api.irail.be/vehicle/?id=BE.NMBS.757&date=201222&format=json&lang=en&alerts=false) can be found as a train, but if you ask the departures on that date on a station (let's say Eke-Nazareth), it doesn't load ("er trad een fout op").

**Comment by Bertware** [comment]
The date is too far in the feature, which is kind of the same issue as when trying to search dates in the past. This could be solved on the iRail side by only using the RIV API for dates in the near future.

**Comment by Bertware** [comment]
@koeleboe I added a fallback datasource by parsing the website, which means you can now also get liveboard data in the past and far future. This is completely transparent for iRail clients. The website lacks information such as if a train has left the station, but this doesn't matter for data in the past and far future. Delays and canceled information are still included.

**Comment by koeleboe** [comment]
It seems to me that the API based on the trainnumber is not working for me. It keeps on loading:
https://api.irail.be/vehicle/?id=510&date=281122&format=json&lang=nl

**Comment by Bertware** [comment]
Fixed! The php process ran out of allowed memory when handling the GTFS file. This in turn caused the lock on the GTFS file to remain "locked" for 300s, meaning all other requests would time out since they were waiting. The memory limit has been raised from 128mb to 256mb. It seems like we were just lucky it worked with 128MB, as the required GTFS files are around 70mb right now. 

Will adjust the locking mechanism (which prevents multiple requests to "race" for the GTFS file, by loading the file once then using cache for the requests which were waiting for the lock) with a lower ttl.

**Comment by Bertware** [comment]
It seems like the cache for vehicle ids was too CPU-intensive, as every request meant that all data for a 14 day period had to been deserialized. This has been solved with more caching at a per-day level, meaning that in typical cases only 1/14th of the data has to be deserialized when reading data.

CPU load dropped by about 40% by applying this fix:
![CPU load when the cache fix is applied](https://user-images.githubusercontent.com/1094793/204390462-05a30606-98fa-4f71-8eb6-8b5d99ffc3e7.png)

At the same time, memory usage dropped, since 80% faster response times lead to memory for those requests being freed 80% faster. Allocating more memory to the cache has therefore lead till a memory usage reduction of about 4GB.

I'm hoping this will solve the last bits of instability which were left, as the system now should have resources to spare in order to handle all requests.

**Comment by koeleboe** [comment]
@Bertware Thanks, works like a charm right now and thank you for the quick solutions always, much appreciated as the new NMBS app really isn't my thing!  However: 

> @koeleboe I added a fallback datasource by parsing the website, which means you can now also get liveboard data in the past and far future. This is completely transparent for iRail clients. The website lacks information such as if a train has left the station, but this doesn't matter for data in the past and far future. Delays and canceled information are still included.

This doesn't seem to work anymore (it did work yesterday) (HTTP error 500). 

Moreover, in the Hyperrail app, some delays of some trains are not shown (if you open a train, the delay is visible). I think it has something to do with the departuresboard. If a train arrives too late at a station (+2) and should depart with +2, the departureboard returns a delay of +0. Why that happens, I have no clue, but I thought I let you know!

**Comment by koeleboe** [comment]
> @Bertware Thanks, works like a charm right now and thank you for the quick solutions always, much appreciated as the new NMBS app really isn't my thing! However:
> 
> > @koeleboe I added a fallback datasource by parsing the website, which means you can now also get liveboard data in the past and far future. This is completely transparent for iRail clients. The website lacks information such as if a train has left the station, but this doesn't matter for data in the past and far future. Delays and canceled information are still included.
> 
> This doesn't seem to work anymore (it did work yesterday) (HTTP error 500).
> 
> Moreover, in the Hyperrail app, some delays of some trains are not shown (if you open a train, the delay is visible). I think it has something to do with the departuresboard. If a train arrives too late at a station (+2) and should depart with +2, the departureboard returns sometimes a delay of +0. It happens mostly when a train has arrived at the station, but has not left the station. Why that happens, I have no clue, but I thought I let you know!

**Comment by Bertware** [comment]
> This doesn't seem to work anymore (it did work yesterday) (HTTP error 500), but maybe the serverload was too high.

While fixing one bug for specific departures without a platform, I introduced a worse one for all departures. Fixed now!

> Moreover, some delays are not shown on the departureboard. It happens when a train has arrived at the station, but has not left the station. I made an example using the API in Sint-Niklaas. This is train IC 732 to Antwerp-Central. As you can see on the first picture (departure board), it shows a delay of 0 minutes. However, when you open the train, it returns a delay of 9 minutes. At Antwerpen-Berchem departure board (last picture), the delay is correctly shown (5 min), but will also dissapear if the train has arrived at the station. This happens also if you try to search in the past (delay is not shown on the departureboard, though it works based on the trainnumber).

Thanks for the clear description! This sounds like an issue with data disappearing in the NMBS data source. Will investigate to see if it is a data issue or an iRail issue.

> Wouldn't it also be helpfull to show more results (https://api.irail.be//liveboard/?id=BE.NMBS.008892650&station=Eke-Nazareth&date=291122&time=1530&arrdep=departure&lang=en&format=json&alerts=false) for a departureboard? Now, you can only see the trains in the coming hour and if you want a later train, a new request has to be done (in stead the trains for the rest of the day are already shown).

This is something that should be implemented client side, as we don't know if the client wants 3 or 300 results. It would also put more logic, and therefore load, on the iRail server. Applications such as hyperrail have continuous scrolling implemented, so it is possible (and relatively easy to apply client-side). Right now we return the data of 1 HTTP requests to the NMBS. Depending on the queried date/time different data sources with different number of results are used. This might be something we can fix once we are completely using the official open data from the NMBS, but in order to do so, the NMBS has to fix a couple of issues in their open data feeds.

**Comment by koeleboe** [comment]
Thank you again for fixing this! However, it seems to me that for some stations the stationboard is still bugged (like Gent-Sint-Pieters) for going in the past. (https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=301122&time=0730&arrdep=departure&lang=en&format=json&alerts=false)

 I've seen that the timetable for the train replacement services (busses) are also not yet working. I don't know if that is an issue on the NMBS side.

**Comment by Bertware** [comment]
The fallback liveboard source is a bit more "sensitive" as the data quality is lower. In this case, the a specific train could not be parsed, which now has been fixed.

**Comment by koeleboe** [comment]
The API seems to work fine for now, however I found a bug concering the arrivals on the liveboard.
- Going back in time results in the same output for the arrival as departure board (except for the first train)
(https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=111222&time=2100&arrdep=arrival&lang=en&format=json&alerts=false)
(https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=111222&time=2100&arrdep=departures&lang=en&format=json&alerts=false)
- The same happens going into the future. Only the timestamp close to the current time gives correct results!

**Comment by Bertware** [comment]
Thanks for reporting this along with the clear examples. This sounds like an issue with the time selection in the fallback datasource, will investigate and fix one of the coming days.

**Comment by Bertware** [comment]
Found the issue and fixed it!

The original URL already contained a parameter, something i didn't check when appending the query string to the url. This caused the first parameter to be ignored, which was the departure/arrival selection. Fixed now!

**Comment by Bertware** [comment]
That's a different issue, Nantes was not included in the iRail/Stations list but is the destination for TGV9832. Fixed by adding Nantes in iRail/Stations (see https://github.com/iRail/stations/commit/556b6c6d3fb737e9600a6e203674c7d8e1d4b119)

**Comment by ChristopheVersieux** [comment]
>  however this is the current timestamp!

This is the current Timestamp: https://api.irail.be//liveboard/?id=BE.NMBS.008892007&station=Gent-Sint-Pieters&date=221222&time=1922&arrdep=departure&lang=en&format=json&alerts=false

**Comment by koeleboe** [comment]
@Bertware For some trains, a weird bug is happening in Hyperrail itself. For example, the S51 train with number 8961. Through the API, everything works fine, however, when you open the train in the app, it gives an error. I'll have a look into it if this issue happens with random other trains too.
https://api.irail.be/vehicle/?id=8961&date=291222&format=json&lang=nl
![321806978_918969542602920_7310733706979817763_n](https://user-images.githubusercontent.com/72651779/209934701-8cf8e709-fd78-4596-9219-ecb5f1e7849d.jpg)

**Comment by koeleboe** [comment]
Replacement services by bus are not shown in the planner (it just skips to the next day with trains) nor can you open the route of the bus.
https://api.irail.be/connections/?to=Eke-Nazareth&from=Gent-Sint-Pieters&format=json
