### ISSUE TITLE
Backwards compatibility testing of new backend code

### ISSUE THREAD

**Issue by Bertware** [iRail/iRail#512]
I've been working a bit on rewriting the existing iRail API, in order to 
- Add new features
- Make it easier to read data from different sources / adapt to changes in data sources
- Ensure API responses always follow the same structure, even when changing things in the backend
- Allow multiple API revisions to exist next to each other (v2 endpoints will be discussed later)
- Make it easier for others to deploy changes / maintain the infrastructure, including better separation for staging and production
- Make the code easier to read, and making it easier for others to contribute to the codebase

The code for this revised API can be found at branch https://github.com/iRail/iRail/tree/feature/laravel-lumen-framework. 
Now I've come to a point where this new backend could replace the currently deployed api.irail.be. All requests should continue working as they do now. The only difference should be a redirect to include `/v1/` in the path, some bug fixes (composition endpoint, liveboard endpoint) and some small improvements, such as spitsgids data which includes official NMBS reports. Some fields may have slight changes in their values, such as the direction name for trains, which now can contain two different station names (as returned by the NMBS).

**Before deploying this change, I'd like for current iRail users to test their current applications against the backwards-compatible test version of this new API**, deployed at https://lumen.api.irail.be/, which will redirect to https://lumen.api.irail.be/v1/.  This is a test version which will be shut down later on, so do not push out any releases using this app, but test it locally by replacing "api.irail.be" with "lumen.api.irail.be".
 
Please report whether you encounter any issues in this thread.

Pinging some of you who have been active in discussions earlier:
@jncn @ChristopheVersieux @vhdirk @koeleboe @muspah @simpyBE

**Comment by centiveo** [comment]
I noticed that the variable NMBS_RIV_API_KEY is needed in this release. This release is based on the API from NMBS and not on GTFS-files?

**Comment by Muspah** [comment]
GTFS at SNCB is a joke. And EPIP an even bigger joke.

**Comment by centiveo** [comment]
I´ve already saw it in another conversation why gtfs is not used ;).

**Comment by Bertware** [comment]
> I noticed that the variable NMBS_RIV_API_KEY is needed in this release. This release is based on the API from NMBS and not on GTFS-files?

Internal NMBS APIs are used in combination with GTFS data. This is how todays implementation works as well, with the only difference that this version relies even more on GTFS to work around certain information not being present in the used data sources.

**Comment by Bertware** [comment]
> https://[lumen.api.irail.be/v1/vehicle/?id=1835](https://lumen.api.irail.be/v1/vehicle/?id=1835) this returns an error: This request failed. Please check your query. Error code API_PARAM but in the original API, this works without a problem https://[api.irail.be/vehicle/?id=1835](https://api.irail.be/vehicle/?id=1835) Maybe this has something to do with cancelled start/end of a trip.

The start was cancelled, which the API can handle. However, the GTFS stop_times reading contained a bug where waypoints (without passenger exchange) were included, which caused the "cancelled train search" function to break. Fixed now, thanks for reporting this! An example train today is ic511.

**Comment by Bertware** [comment]
> I noticed that the times are off by one hour. For example: https://[lumen.api.irail.be/v2/vehicle/660](https://lumen.api.irail.be/v2/vehicle/660) or https://[lumen.api.irail.be/v1/vehicle/?id=660](https://lumen.api.irail.be/v1/vehicle/?id=660) for the latest version gives the departure at Oudenaarde at "scheduledDateTime": "2024-03-14T11:07:00+01:00", but according to the schedule, it should depart at 10:07 our time (so, 09:07 UTC+0 time; or 10:07 UTC+1 time)

This has been corrected now and was caused by incorrect timezone configuration on the server. Thanks for reporting it!

**Comment by koeleboe** [comment]
Liveboards in the future (a week in the future) don't seem to work. In the current API, this is no issue. You get an empty response (with 0 departures).

$https://[api.irail.be/liveboard/?station=Wetteren&date=010524&time=1526&arrdep=departure&lang=en](https://api.irail.be/liveboard/?station=Wetteren&date=010524&time=1526&arrdep=departure&lang=en)

https://[lumen.api.irail.be/v1/liveboard/?station=Wetteren&date=010524&time=1400&arrdep=departure&lang=en](https://lumen.api.irail.be/v1/liveboard/?station=Wetteren&date=010524&time=1400&arrdep=departure&lang=en)

**Comment by koeleboe** [comment]
New difference between the two datastreams. Today, the 3015 is cancelled at some intermediate stops. The lumen api is not able to capture the cancelled stops. Moreover, there are somtimes weird platformnames like "SAS 453"
[api_irail_3015.pdf](https://github.com/iRail/iRail/files/14839086/api_irail_3015.pdf)
[Lumen_api_irail_3015.pdf](https://github.com/iRail/iRail/files/14839088/Lumen_api_irail_3015.pdf)

**Comment by Bertware** [comment]
I implemented a fix for this, by handling "cancelled: true", but when I wanted to verify the intermediate cancellation, I noted this train is also showing strange platforms at the NMBS own site, without cancellations visible:
![NMBS data for train 3015](https://github.com/iRail/iRail/assets/1094793/e9db2401-6090-4f08-89a5-465c844e3ec5)

Even the route planner shows no cancelled stops, while other realtime data is still visible: 
![routeplanning past a cancelled stop](https://github.com/iRail/iRail/assets/1094793/ef070a54-865e-4c23-b49c-b892bd1af507)

Planning a journey to one of the cancelled stops shows that they in fact are cancelled:
![routeplanning to a cancelled stop](https://github.com/iRail/iRail/assets/1094793/645a7498-cf1d-47d3-8eb3-fb14d39c02c7)

The raw data, for future reference
[ic3015.json](https://github.com/iRail/iRail/files/14843270/ic3015.json)

**Comment by Bertware** [comment]
@koeleboe Thanks for the detailed report including dumps of both responses by the way, helped quickly verifying the issue and identifying the case

**Comment by koeleboe** [comment]
You can always check "het vertragingsattest". This gives always the correct route/stops/delays of the trains. As you can see, the stops were indeed canceled. 
https://www.belgiantrain.be/nl/support/customer-service/delay-certificate

**Comment by koeleboe** [comment]
Another difference between the current API and the new is the availability of data in the future. For example; in the current API you can look up months in advance for station liveboards (i guess journeys too, but did not test that). In the new API this feature is not available. If you look at a liveboard for the first of May, you get empty results.

**Comment by Bertware** [comment]
> Another difference between the current API and the new is the availability of data in the future. For example; in the current API you can look up months in advance for station liveboards (i guess journeys too, but did not test that). In the new API this feature is not available. If you look at a liveboard for the first of May, you get empty results.

Fixed now, a fallback datasource will be used when searching more than 3 days in the future and you'll get a correct error message when searching outside the configured iRail timetable period (which can be adjusted when scaling up, when more memory is available). Increasing the limit up to 2 or 3 months should be possible once more memory and processor capacity is added in production. The reason for this is the old API assuming vehicles always start on the date they stop at a station, while the new version correctly determines on which date the vehicle left its first station.

**Comment by LaurentVB** [comment]
Hello. 
I get 504 errors when I query the /composition endpoint on the Lumen API.
First 10 requests work, then it starts to fail. I guess it might be related to [the rate limiting you've just added](https://github.com/iRail/iRail/commit/779b4f9aa361458f8586c94c83c2c74938492d4b). Is the 10 requests/minute a global rate limit, or per client/ip? Can I configure my rate limiter to these values?

**Comment by Bertware** [comment]
The rate limiter is a global limit for the api instance, to ensure the services behind are not disturbed when someone starts scraping irail. It results in only irail going down, instead of both irail and the nmbs services. The current value of 10 is a safe default value and was used for testing, staging and production values haven't been tuned in yet but will be significantly higher. Rate limiting per ip will be added in the same way it is present today, so 1 actor won't be able to consume all outgoing requests.

**Comment by jncn** [comment]
Sorry for the delay! I'll start testing Railer this weekend.

**Comment by koeleboe** [comment]
Something I've been thinking on for a while, which is also not implemented in the "old" API is the changing composition as a train couples or decouples. Now, in the API there is already something in place, for example in the train 736. This train decouples/couples in Kortrijk with a part coming/going to Lille Flandres. As you can see, the train is running with 6 carriages and from Kortrijk to Antwerpen with 9 carriages. 

In the applications now ( i know hyperrail does this), it takes always the longest segment (which is the last, with 9 carriages), but this is technically not correct.

So, if you want to get the right composition for let's say a station between Poperinge and Kortrijk, you have to make another request (as the composition call doesn't get information on where the train exactly is running). 

Moreover, I see that in the second part of the journey, the train number is not yet present (which could give errors to some applications (as Hyperrail, just tested this). 
[train 736.txt](https://github.com/iRail/iRail/files/15094728/train.736.txt)

**Comment by koeleboe** [comment]
Maybe another bug, but I'm currently on the train, so only a screenshot is possible. The IC738 is cancelled from Sint-Niklaas to Antwerpen. However, the train departs from Lokeren (cancelled is false), but the arrival in sint-Niklaas is true. This seems to be a bug.
![Screenshot_20240424_175859_Samsung Internet](https://github.com/iRail/iRail/assets/72651779/956aceff-8eaa-4c5d-a59e-93a192b0e619)

**Comment by jncn** [comment]
Okay, managed to make some time for it today already. 

First of all: great work, happy to see some old stuff, like occupancy, come back to life. Compositions work well too!

The only issue I encountered is that the `lang` parameter seems to be ignored (on XML). All request return English results.

**Comment by jncn** [comment]
> So, if you want to get the right composition for let's say a station between Poperinge and Kortrijk, you have to make another request (as the composition call doesn't get information on where the train exactly is running). Based on that, you can take the right composition, but this seems a sluggish way to get the correct composition.

In Railer, I check the departure station of the journey and determine the right composition based on it. No extra requests needed.

**Comment by koeleboe** [comment]
> > So, if you want to get the right composition for let's say a station between Poperinge and Kortrijk, you have to make another request (as the composition call doesn't get information on where the train exactly is running). Based on that, you can take the right composition, but this seems a sluggish way to get the correct composition.
> 
> In Railer, I check the departure station of the journey and determine the right composition based on it. No extra requests needed.

Yes, that is if you use journeyplanner, if you just open the overview of the train (for example in Hyperrail, based on trainnumber), you don't have that information (or I'm looking at it wrong)?

**Comment by jncn** [comment]
For the train number it's a different story, indeed. For some vehicle requests, where I know the departure station, I choose the relevant composition. For the others, I assume that the first station is also the departure station. In the detail screen, people interested can still get the composition for every part of the journey, though.

**Comment by koeleboe** [comment]
That's clear. I suppose that railer shows multiple compositions of the train (I don't have apple, so i'm guessing). In that way, it is indeed not necessary (but we are going away from the original topic) :D

**Comment by LaurentVB** [comment]
I just stumbled upon another discrepancy, don't know if it's temporary 
https://lumen.api.irail.be/v1/vehicle?id=2118&format=json fails
while https://api.irail.be/vehicle?id=2118&format=json returns a response

**Comment by koeleboe** [comment]
Thanks for the extended response! 

The same issue is btw happening with trains that are departing from a specifc station (where previous stops are being canceled). IC729 departs from Kortrijk, but the API can't handle it very well (departure cancelled, but delay is present).
![Screenshot_20240425_082738_Samsung Internet](https://github.com/iRail/iRail/assets/72651779/070ef983-eb32-454c-97e5-98aa9399d58e)

**Comment by koeleboe** [comment]
> I just stumbled upon another discrepancy, don't know if it's temporary https://lumen.api.irail.be/v1/vehicle?id=2118&format=json fails while https://api.irail.be/vehicle?id=2118&format=json returns a response

The same happens with 3638 today

**Comment by Bertware** [comment]
> > I just stumbled upon another discrepancy, don't know if it's temporary https://lumen.api.irail.be/v1/vehicle?id=2118&format=json fails while https://api.irail.be/vehicle?id=2118&format=json returns a response
> 
> This happens in a certain way too with 3638 today. As well on the API als the new, its not available.

Found a bug causing the "vehicle not found" error not popping up when no journey reference could be found, which in turn led to the invalid request to the NMBS. The error should show up correctly now, but the handling of canceled trains should still be improved.

3638 is cancelled all the way. It may be possible to actually show the trip based on GTFS data it if the "vehicle not found" error always indicates a cancelled vehicle.

Weird enough 2118 brussels - luxemburg on the 24th of April is returning results today, probably since some of the realtime data has been cleared from the NMBS systems. It was however canceled after Namen,

> The same issue is btw happening with trains that are departing from a specifc station (where previous stops are being canceled). IC729 departs from Kortrijk, but the API can't handle it very well (departure cancelled, but delay is present).

Fixed, with a regression test in place on this perfect example (2 cancelled stretches) to ensure the new API keeps handling this correctly. Thanks for these examples!

> What do you exactly mean with this: Occupancy and compositions are to become even better with a new API version to access all data, but for now I'm focusing on getting v1 to work? Are new features added upstream?

There is more data available in the new iRail backend, both due to more data being available upstream (NMBS occupancy levels) as well as data enrichment by the iRail API (historical NMBS occupancy, historical compositions). This new data doesn't fit in the /v1/ responses however, so the old endpoints won't get the data (historical compositions, composition statistics) or gets them in a limited way (v1 occupancy includes NMBS if no spitsgids occupancy reports are available, even though this field was designed for spitsgids only).

**Comment by Bertware** [comment]
> The only issue I encountered is that the lang parameter seems to be ignored (on XML). All request return English results.

This has now been fixed, the translations were cached without taking the language parameter into account, so you got the translation which was loaded first. Language is now taken into account, and a regression test has been added for changing languages.

**Comment by jncn** [comment]
Thanks @Bertware! Honestly, for Railer we're ready to pull the switch. I get too many support e-mails, tweets, etc. about the broken compositions than any of the other small issues we'd still encounter. You have my go 😜

And, Bert, I can't stress this enough: without you none of our project would be possible anymore for a long time. Not sure how to show my gratitude, but please let me know when you're in Belgium.

**Comment by LaurentVB** [comment]
Hello @Bertware 
Encountered a few errors today with the following API requests for composition: 

- https://lumen.api.irail.be/v1/composition/?format=json&id=2112
`"Irail\\Models\\VehicleComposition\\TrainComposition::__construct(): Argument #3 ($destination) must be of type Irail\\Models\\Station, null given, called in /workspace/app/Repositories/Nmbs/NmbsRivCompositionRepository.php on line 105"`

- https://lumen.api.irail.be/v1/composition/?format=json&id=5311
`"Irail\\Models\\VehicleComposition\\TrainComposition::__construct(): Argument #2 ($origin) must be of type Irail\\Models\\Station, null given, called in /workspace/app/Repositories/Nmbs/NmbsRivCompositionRepository.php on line 105"`

- https://lumen.api.irail.be/v1/composition/?format=json&id=5087
`"Undefined property: stdClass::$lastPlanned"`

**Comment by Bertware** [comment]
> "Undefined property: stdClass::$lastPlanned"

This one was caused by only reading one of two planning objects (`lastPlanned`, while ignoring `commercialPlanned`). This case only has `commercialPlanned`, which is (most likely) the plan set up when the timetables are designed, while `lastPlanned` contains the data for the actual composition including exact rolling stock numbers etc. Fixed by using `commercialPlanned` when `lastPlanned` isn't available 

>  `Argument #2 ($origin) must be of type Irail\\Models\\Station, null given`
>  `Argument #3 ($destination) must be of type Irail\\Models\\Station, null given`

These are caused by (foreign) from/to station ids which don't resolve to an actual station, caused by leftover code from Trainmap (which used PTCAR, which in turn maps to TAF/TAP codes for belgian stations). Correct UIC codes are used in the RIV implementation so switching to those fixes the issue.

**Comment by koeleboe** [comment]
Is this a new feature? With some trains in the vehicle call you get the occupancy. This only works for some trains and seems to be random? Or is this data from spitsgids? https://lumen.api.irail.be/v1/vehicle/?id=860

**Comment by Bertware** [comment]
For v1 endpoints, all occupancy data is combined spitsgids/NMBS. NMBS only includes occupancy when using the route planner, but iRail stores this value so it can be used across all endpoints. This means you will see the occupancy if someone has searched for a route that contained the given departure, or when someone reported occupancy through spitsgids. On the staging environment this doesn't do much, but in production it should lead to occupancy data being available for most trains.

**Comment by Bertware** [comment]
There has been some downtime yesterday evening and for the past hour, due to attempts to redirect traffic to the new server. Since HTTPS configuration on the new platform is taking longer than expected, I've pointed the API back to the old server and will make a new attempt this evening when less users are affected.

**Comment by koeleboe** [comment]
I suppose I found a new bug: 
https://lumen.api.irail.be/v1/vehicle/?id=1866

This results in an error
`{"code":0,"request-id":"9be8675a-6bcf-4192-a4a0-aad31621af92","message":"Undefined array key `

**Comment by Bertware** [comment]
> I suppose I found a new bug: https://lumen.api.irail.be/v1/vehicle/?id=1866
> 
> This results in an error `{"code":0,"request-id":"9be8675a-6bcf-4192-a4a0-aad31621af92","message":"Undefined array key `
> 
> It's for al the trains in this series. Maybe it has something to do with the trackworks, as the trains are departing from Melle in stead of Gent, but the old API can handle it.

These trains don't have a direction in the data coming from NMBS. The old version didn't read the field and therefore handled the trains without issues. Fixed with a fallback + regression test.

**Comment by jncn** [comment]
I get an iOS error now, I suppose something went wrong with HTTPS configuration: 
> App Transport Security has blocked a cleartext HTTP connection to `lumen.api.irail.be` since it is insecure. Use HTTPS instead or add this domain to Exception Domains in your Info.plist.

Or has the move not been completed yet?

**Comment by Bertware** [comment]
> I get an iOS error now, I suppose something went wrong with the HTTPS configuration:
> 
> > App Transport Security has blocked a cleartext HTTP connection to `lumen.api.irail.be` since it is insecure. Use HTTPS instead or add this domain to Exception Domains in your Info.plist.
> 
> Or has the move not been completed yet?
> 
> Edit: same issue with `staging.api.irail.be`

I moved the redirect from /connections to /v1/connections from PHP to Nginx, but Nginx seems to downgrade the connection from https to http while doing so since the incoming connection from the load balancer is always HTTP, will fix.

**Comment by Bertware** [comment]
api.irail.be is now running on the new codebase and on the new server platform without issues (after some performance tuning). The server load is quite high (90%) but performance is acceptable, so I'm leaving this deployed and will adjust caching etc later so I can check the effects of changes on a real deployment.

**Comment by jncn** [comment]
Not all heroes wear capes. Thanks for all the hard work @Bertware!

**Comment by ChristopheVersieux** [comment]
Hello

Betrains is currently broken for 2 days and 1 star reviews are coming. I
have no time to check and will remove it from the play store.

I have no time to investigate or to fix.

Thanks.

**Comment by Bertware** [comment]
Most likely the app cannot follow the HTTP 301 redirects. This can be solved by changing the base url from `https://api.irail.be/` to `https://api.irail.be/v1/`, from there on everything should work as usual.

**Comment by ChristopheVersieux** [comment]
Is there a way to get a few extra days with the old url? I will do my best
to update the application ASAP

**Comment by koeleboe** [comment]
Does the spitsgids still work? Untill this evening, I could post occupancy data, but now I get an error. Has this something to do with v1?

**Comment by Bertware** [comment]
> Does the spitsgids still work? Untill this evening, I could post occupancy data, but now I get an error (v1 gives error, normal doesn't). I see that the normal version also is back. Which is now the best version to use?

This is likely a result of reverting to the old urls, which I tried to get BeTrains working again. It seems however like the issue is something else, as I tried BeTrains and results there still won't load. I'll restore the new URLs later today, after I finished another bugfix first.

**Comment by Bertware** [comment]
@ChristopheVersieux I've tried both removing the redirect and removing the strict requirement for a user-agent to be present, but these didn't fix the BeTrains issue and have therefore been restored to the new version.

**Comment by Bertware** [comment]
@ChristopheVersieux I built the app from source and found the problem: the new API doesn't run /connections.php correctly, but returns a 404. Looking for a fix.

**Comment by Bertware** [comment]
Fixed!

**Comment by ChristopheVersieux** [comment]
This is awesome, thanks a lot.
I was able to get my laptop yesterday and pushed a fix as well, hope users
will update their app quickly

Thanks again

**Comment by Bertware** [comment]
Closing this issue since the new codebase is live and there don't seem to be backwards compatibility issues left. Please create a new issue should something pop up. Thanks for testing!

lumen.api.irail.be has been shut down now, new features are tested on staging.api.irail.be again.

**Comment by LaurentVB** [comment]
Congratulations on the successful migration while keeping it all mostly up, that's quite a feat 👏 🎉
